In [7]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[7,4,9],[1,3,4]],dtype='int64')
print(a)
print(b)

[1 2 3]
[[7 4 9]
 [1 3 4]]


In [10]:
print(a.ndim)
print(b.ndim)
print(a.shape)
print(b.shape)
print(a.dtype)
print(b.dtype)
print(a.size)
print(b.size)
print(a.nbytes,b.nbytes)

1
2
(3,)
(2, 3)
int32
int64
3
6
12 48


In [19]:
x=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
x.shape
print(x[1,5])
print(x[1,-2])
print(x[1,:])
print(x[:,4])
print(x[1,2::2])

13
13
[ 8  9 10 11 12 13 14]
[ 5 12]
[10 12 14]


In [25]:
x[0,2:5]=5
print(x)

[[ 5  5  5  5  5  5  5]
 [ 8  9 10 11 12 13 14]]


In [31]:
x[0,1:5:2]=9
print(x)


[[ 5  9  4  9  4  5  5]
 [ 8  9 10 11 12 13 14]]


In [38]:
m=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
n=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(m.shape)
print(n.shape)
print(m[0,1,1])
print(m[0,:,:])
print(m[:,1,:])

(2, 2, 2)
(1, 4, 2)
4
[[1 2]
 [3 4]]
[[3 4]
 [7 8]]


In [40]:
f=np.zeros((3,2))
g=np.zeros((3,2,4))
print(f,g)

[[0. 0.]
 [0. 0.]
 [0. 0.]] [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [41]:
i=np.full((1,2,3),4)
print(i)

[[[4 4 4]
  [4 4 4]]]


In [3]:
import numpy as np
q=np.random.rand(7)

print(q)

[0.23000598 0.949373   0.21069178 0.18998545 0.73094596 0.24886981
 0.52856632]


In [5]:
data = np.linspace(0, 24, 25, dtype=int)
output_array = data.reshape(5, 5)
print(output_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
import pandas as pd
import numpy as np
a=np.arange(0,100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [11]:
ind='r1 r2 r3 r4 r5 r6 r7 r9 r10'.split()
col='c1 c2 c3 c4 c5 c6 c7 c8 c9 c10'.split()
print(ind,col)

['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r9', 'r10'] ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']


In [15]:
import pandas as pd
import numpy as np

a = np.arange(0, 100).reshape(10, 10)
print(a)

ind = 'r1 r2 r3 r4 r5 r6 r7 r8 r9 r10'.split()  # Corrected index labels
col = 'c1 c2 c3 c4 c5 c6 c7 c8 c9 c10'.split()
print(ind, col)

df = pd.DataFrame(data=a, index=ind, columns=col)
print(df)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10'] ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']
     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99


In [19]:
print(df['c5'])
print(df[['c1','c6','c8','c9']])

r1      4
r2     14
r3     24
r4     34
r5     44
r6     54
r7     64
r8     74
r9     84
r10    94
Name: c5, dtype: int32
     c1  c6  c8  c9
r1    0   5   7   8
r2   10  15  17  18
r3   20  25  27  28
r4   30  35  37  38
r5   40  45  47  48
r6   50  55  57  58
r7   60  65  67  68
r8   70  75  77  78
r9   80  85  87  88
r10  90  95  97  98


In [21]:
df['new']=[1,2,3,4,5,6,7,8,9,10]
print(df)

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  new
r1    0   1   2   3   4   5   6   7   8    9    1
r2   10  11  12  13  14  15  16  17  18   19    2
r3   20  21  22  23  24  25  26  27  28   29    3
r4   30  31  32  33  34  35  36  37  38   39    4
r5   40  41  42  43  44  45  46  47  48   49    5
r6   50  51  52  53  54  55  56  57  58   59    6
r7   60  61  62  63  64  65  66  67  68   69    7
r8   70  71  72  73  74  75  76  77  78   79    8
r9   80  81  82  83  84  85  86  87  88   89    9
r10  90  91  92  93  94  95  96  97  98   99   10


In [22]:
df.drop('new',axis=1,inplace=True)
print(df)

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99


In [24]:
print(df.loc[['r1','r2']])


    c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1   0   1   2   3   4   5   6   7   8    9
r2  10  11  12  13  14  15  16  17  18   19


In [25]:
print(df.iloc[[0,1]])

    c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1   0   1   2   3   4   5   6   7   8    9
r2  10  11  12  13  14  15  16  17  18   19


In [31]:
#intersection

print(df.loc[['r2','r6'], ['c3']])

    c3
r2  12
r6  52


In [38]:
r=df[df['c1']>30]
print(r)
w=df['c2']>40
print(w)

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99
r1     False
r2     False
r3     False
r4     False
r5      True
r6      True
r7      True
r8      True
r9      True
r10     True
Name: c2, dtype: bool


In [39]:
df[df['c3']>40][['c3','c6']]

c3  c6
r5   42  45
r6   52  55
r7   62  65
r8   72  75
r9   82  85
r10  92  95

In [41]:
i=df[(df['c1']>60) & (df['c2']>80)][['c4','c6']]
print(i)

     c4  c6
r9   83  85
r10  93  95


In [42]:
df.head()
df.tail()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, r1 to r10
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      10 non-null     int32
 1   c2      10 non-null     int32
 2   c3      10 non-null     int32
 3   c4      10 non-null     int32
 4   c5      10 non-null     int32
 5   c6      10 non-null     int32
 6   c7      10 non-null     int32
 7   c8      10 non-null     int32
 8   c9      10 non-null     int32
 9   c10     10 non-null     int32
dtypes: int32(10)
memory usage: 780.0+ bytes


In [43]:
df.describe()

c1         c2         c3         c4         c5         c6  \
count  10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
mean   45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
std    30.276504  30.276504  30.276504  30.276504  30.276504  30.276504   
min     0.000000   1.000000   2.000000   3.000000   4.000000   5.000000   
25%    22.500000  23.500000  24.500000  25.500000  26.500000  27.500000   
50%    45.000000  46.000000  47.000000  48.000000  49.000000  50.000000   
75%    67.500000  68.500000  69.500000  70.500000  71.500000  72.500000   
max    90.000000  91.000000  92.000000  93.000000  94.000000  95.000000   

              c7         c8         c9        c10  
count  10.000000  10.000000  10.000000  10.000000  
mean   51.000000  52.000000  53.000000  54.000000  
std    30.276504  30.276504  30.276504  30.276504  
min     6.000000   7.000000   8.000000   9.000000  
25%    28.500000  29.500000  30.500000  31.500000  
50%    51.000000  52.000000  53.000000  54.000000  
75%    73.500000  74.500000  75.500000  76.500000  
max    96.000000  97.000000  98.000000  99.000000

In [47]:

import pandas as pd

# Use double backslashes or a raw string for the file path
df3 = pd.read_csv(r'C:\Users\tahmi\Downloads\2023-08-09T16-44-25.111Z-Breast_Cancer_Diagnostic.csv')

# Now you can work with the DataFrame df3
print(df3)


           id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compa

In [48]:
df3.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  ...  texture_worst  perimeter_worst   area_worst  \
count     569.000000  ...     569.000000       569.000000   569.000000   
mean        0.181162  ...      25.677223       107.261213   880.583128   
std         0.027414  ...       6.146258        33.602542   569.356993   
min         0.106000  ...      12.020000        50.410000   185.200000   
25%         0.161900  ...      21.080000        84.110000   515.300000   
50%         0.179200  ...      25.410000        97.660000   686.500000   
75%         0.195700  ...      29.720000       125.400000  1084.000000   
max         0.304000  ...      49.540000       251.200000  4254.000000   

       smoothness_worst  compactness_worst  concavity_worst  \
count        569.000000         569.000000       569.000000   
mean           0.132369           0.254265         0.272188   
std            0.022832           0.157336         0.208624   
min            0.071170           0.027290         0.000000   
25%            0.116600           0.147200         0.114500   
50%            0.131300           0.211900         0.226700   
75%            0.146000           0.339100         0.382900   
max            0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  \
count            569.000000      569.000000               569.000000   
mean               0.114606        0.290076                 0.083946   
std                0.065732        0.061867                 0.018061   
min                0.000000        0.156500                 0.055040   
25%                0.064930        0.250400                 0.071460   
50%                0.099930        0.282200                 0.080040   
75%                0.161400        0.317900                 0.092080   
max                0.291000        0.663800                 0.207500   

       Unnamed: 32  
count          0.0  
mean           NaN  
std            NaN  
min            NaN  
25%            NaN  
50%            NaN  
75%            NaN  
max            NaN  

[8 rows x 32 columns]

In [56]:
# Reading from python dictionary
d1={'key':['a','b','c','d','e'],
   'A1':range(5),
   'B1':range(5,10)
  }
d2={'key':['a','b','c'],
   'A1':range(3),
   'B1':range(3,6)
  }
df4=pd.DataFrame(d1)
df5=pd.DataFrame(d2)
print(df4)
print(df5)


  key  A1  B1
0   a   0   5
1   b   1   6
2   c   2   7
3   d   3   8
4   e   4   9
  key  A1  B1
0   a   0   3
1   b   1   4
2   c   2   5


# merging two dataframes

In [58]:
df6=pd.merge(df4,df5,how='left',on='key')
print(df6)
df6=pd.merge(df4,df5,how='right',on='key')
print(df6)
df6=pd.merge(df4,df5,how='inner',on='key')
print(df6)
df6=pd.merge(df4,df5,how='outer',on='key')
print(df6)

  key  A1_x  B1_x  A1_y  B1_y
0   a     0     5   0.0   3.0
1   b     1     6   1.0   4.0
2   c     2     7   2.0   5.0
3   d     3     8   NaN   NaN
4   e     4     9   NaN   NaN
  key  A1_x  B1_x  A1_y  B1_y
0   a     0     5     0     3
1   b     1     6     1     4
2   c     2     7     2     5
  key  A1_x  B1_x  A1_y  B1_y
0   a     0     5     0     3
1   b     1     6     1     4
2   c     2     7     2     5
  key  A1_x  B1_x  A1_y  B1_y
0   a     0     5   0.0   3.0
1   b     1     6   1.0   4.0
2   c     2     7   2.0   5.0
3   d     3     8   NaN   NaN
4   e     4     9   NaN   NaN


In [59]:
df1=pd.DataFrame({'key1':['a','b','c','d','e'],
              'key2':['A','B','C','D','E'],
   'A1':range(5),
   'B1':range(5,10)
  })
df2=pd.DataFrame({'key1':['a','b','c'],
              'key2':['A','B','C'],
   'A1':range(3),
   'B1':range(3,6)
  })
df3=pd.merge(df1,df2,how='outer',on=['key1','key2'])
print(df3)


  key1 key2  A1_x  B1_x  A1_y  B1_y
0    a    A     0     5   0.0   3.0
1    b    B     1     6   1.0   4.0
2    c    C     2     7   2.0   5.0
3    d    D     3     8   NaN   NaN
4    e    E     4     9   NaN   NaN


In [5]:
import pandas as pd
import numpy as np
df1=pd.DataFrame({ 'A':['A0','A1','A2','A3'],
                  'B':['B0','B1','B2','B3'],
                     'C' : ['C0','C1','C2','C3'],
                    'D' :  ['D0','D1','D2','D3']},
                  index=[0,1,2,3])
    
    

print(df1)
df2=pd.DataFrame({ 'A':['A4','A5','A6','A7'],
                  'B':['B4','B5','B26','B7'],
                     'C' : ['C4','C5','C6','C7'],
                    'D' :  ['D4','D5','D6','D7']},
                  index=[4,5,6,7])
print(df2)
    

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
    A    B   C   D
4  A4   B4  C4  D4
5  A5   B5  C5  D5
6  A6  B26  C6  D6
7  A7   B7  C7  D7


In [6]:
pd.concat([df1,df2])

A    B   C   D
0  A0   B0  C0  D0
1  A1   B1  C1  D1
2  A2   B2  C2  D2
3  A3   B3  C3  D3
4  A4   B4  C4  D4
5  A5   B5  C5  D5
6  A6  B26  C6  D6
7  A7   B7  C7  D7

In [18]:
import pandas as pd

data = {'Store': ['Walmart', 'Walmart', 'Costco', 'Costco', 'Target', 'Target'],
        'Customer': ['Tim', 'Jeremy', 'Mark', 'Denice', 'Ray', 'Sam'],
        'Sales': [150, 200, 550, 90, 430, 120]}

df = pd.DataFrame(data)
print(df)

store_grouped = df.groupby("Store").sum()
print(store_grouped)


     Store Customer  Sales
0  Walmart      Tim    150
1  Walmart   Jeremy    200
2   Costco     Mark    550
3   Costco   Denice     90
4   Target      Ray    430
5   Target      Sam    120
           Customer  Sales
Store                     
Costco   MarkDenice    640
Target       RaySam    550
Walmart   TimJeremy    350


In [10]:
df.groupby("Store").count()

Customer  Sales
Store                   
Costco          2      2
Target          2      2
Walmart         2      2

In [12]:
df.groupby("Store").count()[['Sales']]

Sales
Store         
Costco       2
Target       2
Walmart      2

In [23]:
import pandas as pd

data = {'Store': ['Walmart', 'Walmart', 'Costco', 'Costco', 'Target', 'Target'],
        'Customer': ['Tim', 'Jeremy', 'Mark', 'Denice', 'Ray', 'Sam'],
        'Sales': [150, 200, 550, 90, 430, 120]}

df = pd.DataFrame(data)
print(df)

by_store = df.groupby("Store")
sum1 = by_store[['Sales']].sum()  # Calculate sum of 'Sales' for each store
print(sum1)

mean1 = by_store[['Sales']].mean()  # Calculate mean of 'Sales' for each store
print(mean1)
sum1['mean']=mean1['Sales']
sum1

     Store Customer  Sales
0  Walmart      Tim    150
1  Walmart   Jeremy    200
2   Costco     Mark    550
3   Costco   Denice     90
4   Target      Ray    430
5   Target      Sam    120
         Sales
Store         
Costco     640
Target     550
Walmart    350
         Sales
Store         
Costco   320.0
Target   275.0
Walmart  175.0


Sales   mean
Store                
Costco     640  320.0
Target     550  275.0
Walmart    350  175.0

In [24]:
import pandas as pd

data = {'Store': ['Walmart', 'Walmart', 'Costco', 'Costco', 'Target', 'Target'],
        'Customer': ['Tim', 'Jeremy', 'Mark', 'Denice', 'Ray', 'Sam'],
        'Sales': [150, 200, 550, 90, 430, 120]}

df = pd.DataFrame(data)
print(df)

by_store = df.groupby("Store")
by_store.sum().loc[["Target"]]


     Store Customer  Sales
0  Walmart      Tim    150
1  Walmart   Jeremy    200
2   Costco     Mark    550
3   Costco   Denice     90
4   Target      Ray    430
5   Target      Sam    120


Customer  Sales
Store                 
Target   RaySam    550

In [26]:
import pandas as pd

data = {'Store': ['Walmart', 'Walmart', 'Costco', 'Costco', 'Target', 'Target'],
        'Customer': ['Tim', 'Jeremy', 'Mark', 'Denice', 'Ray', 'Sam'],
        'Sales': [150, 200, 550, 90, 430, 120]}

df = pd.DataFrame(data)

by_store = df.groupby("Store")

min_sales = by_store['Sales'].min()  # Minimum 'Sales' for each store
max_sales = by_store['Sales'].max()  # Maximum 'Sales' for each store
std_dev_sales = by_store['Sales'].std()  # Standard deviation of 'Sales' for each store

print("Minimum Sales:")
print(min_sales)

print("\nMaximum Sales:")
print(max_sales)

print("\nStandard Deviation of Sales:")
print(std_dev_sales)


Minimum Sales:
Store
Costco      90
Target     120
Walmart    150
Name: Sales, dtype: int64

Maximum Sales:
Store
Costco     550
Target     430
Walmart    200
Name: Sales, dtype: int64

Standard Deviation of Sales:
Store
Costco     325.269119
Target     219.203102
Walmart     35.355339
Name: Sales, dtype: float64


In [28]:
import pandas as pd
data_dic = {'M':[1,2,np.nan,4,np.nan],
            'N':[11,12,13,14,15],
            'O':[np.nan,np.nan,np.nan,np.nan,np.nan],
            'P':[16,np.nan,18,19,20]}
df = pd.DataFrame(data_dic) # dataframe from a dic.
df.isnull()


M      N     O      P
0  False  False  True  False
1  False  False  True   True
2   True  False  True  False
3  False  False  True  False
4   True  False  True  False

In [30]:
import pandas as pd

data = {'Store': ['Walmart', 'Walmart', 'Costco', 'Costco', 'Target', 'Target'],
        'Customer': ['Tim', 'Jeremy', 'Mark', 'Denice', 'Ray', 'Sam'],
        'Sales': [150, 200, 550, 90, 430, 120]}

df = pd.DataFrame(data)

by_store = df.groupby("Store")
by_store.describe()
by_store.describe().transpose()

Store            Costco      Target     Walmart
Sales count    2.000000    2.000000    2.000000
      mean   320.000000  275.000000  175.000000
      std    325.269119  219.203102   35.355339
      min     90.000000  120.000000  150.000000
      25%    205.000000  197.500000  162.500000
      50%    320.000000  275.000000  175.000000
      75%    435.000000  352.500000  187.500000
      max    550.000000  430.000000  200.000000

# Missing Data

In [31]:
data_dic = {'A':[1,2,np.nan,4,np.nan],
            'B':[np.nan,np.nan,np.nan,np.nan,np.nan],
            'C':[11,12,13,14,15],
            'D':[16,np.nan,18,19,20]}
df = pd.DataFrame(data_dic)
df.isnull()

A     B      C      D
0  False  True  False  False
1  False  True  False   True
2   True  True  False  False
3  False  True  False  False
4   True  True  False  False

In [32]:
df.isnull().sum()

A    2
B    5
C    0
D    1
dtype: int64

In [33]:
df.isnull().sum().sum()

8

In [35]:
df.loc[4].isnull().sum()

2

In [36]:
print(df.shape)

(5, 4)


In [37]:
df.dropna(axis=0 )

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [38]:
df.dropna(thresh=2,axis=1)

A   C     D
0  1.0  11  16.0
1  2.0  12   NaN
2  NaN  13  18.0
3  4.0  14  19.0
4  NaN  15  20.0

In [39]:
df.fillna(value='a')

A  B   C     D
0  1.0  a  11  16.0
1  2.0  a  12     a
2    a  a  13  18.0
3  4.0  a  14  19.0
4    a  a  15  20.0

In [40]:
df['A'].fillna(value=df['A'].mean())

0    1.000000
1    2.000000
2    2.333333
3    4.000000
4    2.333333
Name: A, dtype: float64

In [41]:
df.fillna(method='ffill')

A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12  16.0
2  2.0 NaN  13  18.0
3  4.0 NaN  14  19.0
4  4.0 NaN  15  20.0